# This file contains the [pre-commit](https://pre-commit.com/) configuration of this repository.
# More on which specific pre-commit hooks we use can be found in README.md.
---
minimum_pre_commit_version: "2.9.2"
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff --force-exclude
        language: python
        types_or: [ python, pyi ]
        require_serial: true
        additional_dependencies:
          - ruff==0.1.4
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: python
        types_or: [ python, pyi ]
        require_serial: true
        additional_dependencies:
          - ruff==0.1.4
      - id: mypy
        name: mypy - Static type checking
        description: Mypy helps ensure that we use our functions and variables correctly by checking the types.
        entry: mypy
        args:
          - --install-types
          - --non-interactive
          - --ignore-missing-imports
          - --scripts-are-modules
          - --strict
        language: system  # By using system, we ensure we use the venv of the user and thus use all installed packages.
        types:
          - python
        require_serial: true
