---
version: "2.1"
services:
  postgres:
    container_name: duty_database
    image: registry.hub.docker.com/library/postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  frontend:
    container_name: duty_frontend
    image: registry.hub.docker.com/library/node:18-slim
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
    volumes:
      - ./duty_board/www:/code
    working_dir: /code
    command: /bin/bash -c "npm install && npm run dev2"

  backend:
    depends_on:
      - postgres
    container_name: duty_backend
    image: registry.hub.docker.com/library/python:3.10-slim
    ports:
      - 8000:8000
    links:
      - "postgres:database_container"
    environment:
      - NODE_ENV=development
      - SQL_ALCHEMY_CONNECTION=postgresql://postgres:mysecretpassword@database_container:5432/postgres
      - DUTY_BOARD_SECRET_KEY=RANDOM_SECRET_KEY
      - CREATE_DUMMY_RECORDS=1
    volumes:
      - ./:/code
      - ./docker_venv:/venv
      # Prevent docker_venv from being synced into the container twice; https://stackoverflow.com/a/37898591/2277445
      - /code/docker_venv
      - /code/docker_prod_venv
      - /code/duty_board/www/node_modules
    working_dir: /code
    command: /bin/bash -c "python3 -m venv /venv && source /venv/bin/activate && pip3 install -e . && uvicorn duty_board.server:app --host 0.0.0.0 --port 8000 --reload"
