"""store-image-in-db

Revision ID: 2df94475917e
Revises: 25f00fd34f6a
Create Date: 2023-11-27 12:02:06.354626

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2df94475917e"
down_revision: Union[str, None] = "25f00fd34f6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person_image",
        sa.Column("uid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("image_in_bytes", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.alter_column("calendar", "icalendar_url", existing_type=sa.VARCHAR(length=500), nullable=False)
    op.create_unique_constraint("on_call_event.uid.unique", "on_call_event", ["uid"])
    op.add_column("person", sa.Column("image_uid", sa.Integer(), nullable=True))
    op.drop_index("person_last_update_utc", table_name="person")
    op.create_unique_constraint("person.image_uid.unique", "person", ["image_uid"])
    op.create_unique_constraint("person.uid.unique", "person", ["uid"])
    op.create_foreign_key("person.image_uid.foreign_key", "person", "person_image", ["image_uid"], ["uid"])
    op.drop_column("person", "img_filename")
    op.alter_column("token", "username", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.create_unique_constraint("token.token.unique", "token", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("token.token.unique", "token", type_="unique")
    op.alter_column("token", "username", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.add_column("person", sa.Column("img_filename", sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint("person.image_uid.foreign_key", "person", type_="foreignkey")
    op.drop_constraint("person.uid.unique", "person", type_="unique")
    op.drop_constraint("person.image_uid.unique", "person", type_="unique")
    op.create_index("person_last_update_utc", "person", ["last_update_utc"], unique=False)
    op.drop_column("person", "image_uid")
    op.drop_constraint("on_call_event.uid.unique", "on_call_event", type_="unique")
    op.alter_column("calendar", "icalendar_url", existing_type=sa.VARCHAR(length=500), nullable=True)
    op.drop_table("person_image")
    # ### end Alembic commands ###
